CREATE TABLE IF NOT EXISTS regen_protocol_drafts (
    tenant_id VARCHAR(128) NOT NULL,
    protocol_id VARCHAR(128) NOT NULL,
    title VARCHAR(255) NOT NULL,
    content_json TEXT NOT NULL,
    updated_by VARCHAR(128) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, protocol_id)
);

CREATE TABLE IF NOT EXISTS regen_protocol_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    protocol_id VARCHAR(128) NOT NULL,
    version INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    content_json TEXT NOT NULL,
    published_by VARCHAR(128) NOT NULL,
    changelog TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, protocol_id, version)
);

CREATE INDEX IF NOT EXISTS idx_regen_protocol_versions_lookup
    ON regen_protocol_versions (tenant_id, protocol_id, version DESC);

CREATE TABLE IF NOT EXISTS regen_runs (
    tenant_id VARCHAR(128) NOT NULL,
    run_id VARCHAR(128) NOT NULL,
    protocol_id VARCHAR(128) NOT NULL,
    protocol_version INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL,
    gateway_id VARCHAR(128),
    started_by VARCHAR(128) NOT NULL,
    abort_reason TEXT,
    started_at TIMESTAMP NOT NULL,
    paused_at TIMESTAMP,
    aborted_at TIMESTAMP,
    updated_at TIMESTAMP NOT NULL,
    PRIMARY KEY (tenant_id, run_id)
);

CREATE INDEX IF NOT EXISTS idx_regen_runs_tenant_updated
    ON regen_runs (tenant_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS regen_run_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    run_id VARCHAR(128) NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    source VARCHAR(64) NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (tenant_id, run_id) REFERENCES regen_runs(tenant_id, run_id)
);

CREATE INDEX IF NOT EXISTS idx_regen_run_events_stream
    ON regen_run_events (tenant_id, run_id, created_at ASC, id ASC);

CREATE TABLE IF NOT EXISTS regen_run_telemetry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    run_id VARCHAR(128) NOT NULL,
    gateway_id VARCHAR(128) NOT NULL,
    metric_key VARCHAR(128) NOT NULL,
    metric_value DOUBLE PRECISION NOT NULL,
    unit VARCHAR(32) NOT NULL,
    drift_score DOUBLE PRECISION NOT NULL,
    recorded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (tenant_id, run_id) REFERENCES regen_runs(tenant_id, run_id)
);

CREATE INDEX IF NOT EXISTS idx_regen_run_telemetry_stream
    ON regen_run_telemetry (tenant_id, run_id, recorded_at ASC, id ASC);

CREATE TABLE IF NOT EXISTS regen_gateways (
    tenant_id VARCHAR(128) NOT NULL,
    gateway_id VARCHAR(128) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    certificate_serial VARCHAR(256),
    status VARCHAR(32) NOT NULL,
    last_heartbeat_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, gateway_id)
);

CREATE TABLE IF NOT EXISTS regen_drift_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    run_id VARCHAR(128) NOT NULL,
    severity VARCHAR(32) NOT NULL,
    metric_key VARCHAR(128) NOT NULL,
    metric_value DOUBLE PRECISION NOT NULL,
    threshold DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_regen_drift_alerts_run
    ON regen_drift_alerts (tenant_id, run_id, created_at DESC);

CREATE TABLE IF NOT EXISTS regen_evidence_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    action_type VARCHAR(128) NOT NULL,
    actor_id VARCHAR(128) NOT NULL,
    resource_type VARCHAR(128) NOT NULL,
    resource_id VARCHAR(128) NOT NULL,
    payload_json TEXT NOT NULL,
    payload_hash VARCHAR(64) NOT NULL,
    prev_hash VARCHAR(64),
    event_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_regen_evidence_chain
    ON regen_evidence_events (tenant_id, id ASC);

CREATE INDEX IF NOT EXISTS idx_regen_evidence_resource
    ON regen_evidence_events (tenant_id, resource_type, resource_id, id ASC);
