CREATE TABLE IF NOT EXISTS admin_tenants (
    tenant_id VARCHAR(128) PRIMARY KEY,
    name VARCHAR(256) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin_sites (
    tenant_id VARCHAR(128) NOT NULL,
    site_id VARCHAR(128) NOT NULL,
    name VARCHAR(256) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, site_id)
);

CREATE TABLE IF NOT EXISTS admin_feature_flags (
    tenant_id VARCHAR(128) NOT NULL,
    flag_key VARCHAR(128) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(128) NOT NULL,
    PRIMARY KEY (tenant_id, flag_key)
);
