CREATE TABLE IF NOT EXISTS telemetry_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    printer_id VARCHAR(128) NOT NULL,
    timestamp_ms BIGINT NOT NULL,
    nozzle_temp_celsius REAL NOT NULL,
    extrusion_pressure_kpa REAL NOT NULL,
    cell_viability_index REAL NOT NULL,
    encrypted_image_matrix_base64 TEXT NOT NULL,
    source VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_telemetry_events_printer_ts
    ON telemetry_events(printer_id, timestamp_ms DESC);

CREATE TABLE IF NOT EXISTS control_commands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command_id VARCHAR(128) NOT NULL UNIQUE,
    printer_id VARCHAR(128) NOT NULL,
    action_type VARCHAR(32) NOT NULL,
    adjust_pressure REAL NOT NULL,
    adjust_speed REAL NOT NULL,
    reason VARCHAR(1024) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_control_commands_printer_created
    ON control_commands(printer_id, created_at DESC);

CREATE TABLE IF NOT EXISTS digital_twin_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    printer_id VARCHAR(128) NOT NULL,
    updated_at_ms BIGINT NOT NULL,
    current_viability REAL NOT NULL,
    predicted_viability_5m REAL NOT NULL,
    collapse_risk_score REAL NOT NULL,
    recommended_action VARCHAR(32) NOT NULL,
    confidence REAL NOT NULL,
    UNIQUE(printer_id)
);

CREATE TABLE IF NOT EXISTS clinical_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type VARCHAR(16) NOT NULL,
    external_id VARCHAR(256),
    patient_id VARCHAR(256),
    content TEXT NOT NULL,
    metadata_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_clinical_documents_patient
    ON clinical_documents(patient_id, created_at DESC);

CREATE TABLE IF NOT EXISTS audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor VARCHAR(256) NOT NULL,
    action VARCHAR(128) NOT NULL,
    resource_type VARCHAR(128) NOT NULL,
    resource_id VARCHAR(256),
    outcome VARCHAR(32) NOT NULL,
    requirement_ids VARCHAR(512) NOT NULL,
    details_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_events_created
    ON audit_events(created_at DESC);
