ALTER TABLE telemetry_events
    ADD COLUMN IF NOT EXISTS bio_ink_viscosity_index REAL DEFAULT 0.0;

ALTER TABLE telemetry_events
    ADD COLUMN IF NOT EXISTS bio_ink_ph REAL DEFAULT 7.4;

ALTER TABLE telemetry_events
    ADD COLUMN IF NOT EXISTS nir_ii_temp_celsius REAL DEFAULT 37.0;

ALTER TABLE telemetry_events
    ADD COLUMN IF NOT EXISTS morphological_defect_probability REAL DEFAULT 0.0;

ALTER TABLE telemetry_events
    ADD COLUMN IF NOT EXISTS print_job_id VARCHAR(128) DEFAULT '';

ALTER TABLE telemetry_events
    ADD COLUMN IF NOT EXISTS tissue_type VARCHAR(64) DEFAULT 'retina';

CREATE TABLE IF NOT EXISTS retinal_print_plans (
    plan_id VARCHAR(128) PRIMARY KEY,
    patient_id VARCHAR(256) NOT NULL,
    source_document_id VARCHAR(256),
    blueprint_version VARCHAR(64) NOT NULL,
    layers_json TEXT NOT NULL,
    constraints_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_retinal_plans_patient
    ON retinal_print_plans(patient_id, created_at DESC);

CREATE TABLE IF NOT EXISTS print_sessions (
    session_id VARCHAR(128) PRIMARY KEY,
    printer_id VARCHAR(128) NOT NULL,
    plan_id VARCHAR(128) NOT NULL,
    patient_id VARCHAR(256) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_print_sessions_printer_status
    ON print_sessions(printer_id, status, updated_at DESC);

CREATE TABLE IF NOT EXISTS latency_budget_breaches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    printer_id VARCHAR(128) NOT NULL,
    source VARCHAR(32) NOT NULL,
    duration_ms DOUBLE PRECISION NOT NULL,
    threshold_ms BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_latency_breaches_created
    ON latency_budget_breaches(created_at DESC);

CREATE TABLE IF NOT EXISTS integration_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(128) NOT NULL,
    partition_key VARCHAR(256) NOT NULL,
    payload_json TEXT NOT NULL,
    status VARCHAR(32) NOT NULL,
    attempts INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_outbox_status_id
    ON integration_outbox(status, id);
