ALTER TABLE integration_outbox
    ADD COLUMN IF NOT EXISTS next_attempt_at TIMESTAMP;

ALTER TABLE integration_outbox
    ADD COLUMN IF NOT EXISTS last_error VARCHAR(2048);

UPDATE integration_outbox
SET next_attempt_at = created_at
WHERE next_attempt_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_outbox_next_attempt
    ON integration_outbox(status, next_attempt_at, id);

CREATE TABLE IF NOT EXISTS integration_outbox_dead_letter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_outbox_id BIGINT NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    partition_key VARCHAR(256) NOT NULL,
    payload_json TEXT NOT NULL,
    attempts INT NOT NULL,
    failure_reason VARCHAR(2048) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    failed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_outbox_dlq_failed_at
    ON integration_outbox_dead_letter(failed_at DESC);
