ALTER TABLE audit_events
    ADD COLUMN IF NOT EXISTS previous_hash VARCHAR(128);

ALTER TABLE audit_events
    ADD COLUMN IF NOT EXISTS event_hash VARCHAR(128);

CREATE INDEX IF NOT EXISTS idx_audit_events_hash
    ON audit_events(event_hash);

ALTER TABLE clinical_documents
    ADD COLUMN IF NOT EXISTS anonymized_at TIMESTAMP;

ALTER TABLE clinical_documents
    ADD COLUMN IF NOT EXISTS retention_until TIMESTAMP;

ALTER TABLE clinical_documents
    ADD COLUMN IF NOT EXISTS data_classification VARCHAR(32);

ALTER TABLE clinical_documents
    ADD COLUMN IF NOT EXISTS key_id VARCHAR(128);

CREATE TABLE IF NOT EXISTS gdpr_consents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id VARCHAR(256) NOT NULL,
    purpose VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    legal_basis VARCHAR(128) NOT NULL,
    granted_by VARCHAR(256) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_gdpr_consents_patient_purpose
    ON gdpr_consents(patient_id, purpose, created_at DESC);

CREATE TABLE IF NOT EXISTS gdpr_erasure_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id VARCHAR(256) NOT NULL,
    requested_by VARCHAR(256) NOT NULL,
    reason VARCHAR(1024) NOT NULL,
    outcome VARCHAR(64) NOT NULL,
    affected_rows INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_gdpr_erasure_created
    ON gdpr_erasure_requests(created_at DESC);
