CREATE TABLE IF NOT EXISTS request_idempotency (
    operation VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(256) NOT NULL,
    payload_hash VARCHAR(128) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    PRIMARY KEY (operation, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_request_idempotency_expires
    ON request_idempotency(expires_at);

CREATE TABLE IF NOT EXISTS capa_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(256) NOT NULL,
    description VARCHAR(2048) NOT NULL,
    requirement_id VARCHAR(64) NOT NULL,
    owner VARCHAR(256) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_capa_records_updated
    ON capa_records(updated_at DESC);

CREATE TABLE IF NOT EXISTS risk_register (
    risk_id VARCHAR(128) PRIMARY KEY,
    hazard_description VARCHAR(2048) NOT NULL,
    severity INT NOT NULL,
    probability INT NOT NULL,
    detectability INT NOT NULL,
    controls VARCHAR(4096) NOT NULL,
    residual_risk_level INT NOT NULL,
    linked_requirement_id VARCHAR(64),
    owner VARCHAR(256) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_risk_register_updated
    ON risk_register(updated_at DESC);

CREATE TABLE IF NOT EXISTS dhf_artifacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artifact_type VARCHAR(128) NOT NULL,
    artifact_name VARCHAR(256) NOT NULL,
    version VARCHAR(64) NOT NULL,
    location VARCHAR(2048) NOT NULL,
    checksum_sha256 VARCHAR(128) NOT NULL,
    approved_by VARCHAR(256) NOT NULL,
    approved_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_dhf_artifacts_approved
    ON dhf_artifacts(approved_at DESC);
