CREATE TABLE IF NOT EXISTS roles (
    name VARCHAR(32) PRIMARY KEY
);

INSERT INTO roles(name) SELECT 'ADMIN' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ADMIN');
INSERT INTO roles(name) SELECT 'OPERATOR' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'OPERATOR');
INSERT INTO roles(name) SELECT 'AUDITOR' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'AUDITOR');
INSERT INTO roles(name) SELECT 'INTEGRATION' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'INTEGRATION');

CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(64) PRIMARY KEY,
    username VARCHAR(128) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(32) NOT NULL REFERENCES roles(name),
    tenant_id VARCHAR(128),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_users_username_active
    ON users(username, is_active);

CREATE TABLE IF NOT EXISTS devices (
    id VARCHAR(128) PRIMARY KEY,
    tenant_id VARCHAR(128),
    name VARCHAR(256) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS print_jobs (
    id VARCHAR(128) PRIMARY KEY,
    device_id VARCHAR(128) NOT NULL REFERENCES devices(id),
    tenant_id VARCHAR(128),
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_print_jobs_device_status
    ON print_jobs(device_id, status, updated_at DESC);

CREATE TABLE IF NOT EXISTS telemetry_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id VARCHAR(128) NOT NULL REFERENCES print_jobs(id),
    device_id VARCHAR(128) NOT NULL REFERENCES devices(id),
    payload_json TEXT NOT NULL,
    recorded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_telemetry_records_job_ts
    ON telemetry_records(job_id, recorded_at DESC);

CREATE TABLE IF NOT EXISTS digital_twin_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id VARCHAR(128) NOT NULL REFERENCES print_jobs(id),
    device_id VARCHAR(128) NOT NULL REFERENCES devices(id),
    payload_json TEXT NOT NULL,
    recorded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_digital_twin_metrics_job_ts
    ON digital_twin_metrics(job_id, recorded_at DESC);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id VARCHAR(128),
    actor_id VARCHAR(128) NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    device_id VARCHAR(128),
    payload_json TEXT NOT NULL,
    payload_hash VARCHAR(64) NOT NULL,
    prev_hash VARCHAR(64),
    event_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_job_id_created
    ON audit_logs(job_id, created_at ASC, id ASC);

CREATE INDEX IF NOT EXISTS idx_audit_logs_job_hash
    ON audit_logs(job_id, event_hash);

CREATE TABLE IF NOT EXISTS health_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(32) NOT NULL,
    details VARCHAR(512) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
